Update (#1432)
Update deployments

diff --git a/biosimulations/tools/docker-build b/biosimulations/tools/docker-build
--- a/biosimulations/tools/docker-build
+++ b/biosimulations/tools/docker-build
@@ -1,11 +1,25 @@
 #!/usr/bin/env bash
 COMMIT=$(git rev-parse HEAD)
-:"${DOCKER_BUILD_CONTEXT:=..}" "${DOCKER_BACKEND_PATH=../Dockerfile}" "${TAG:=$COMMIT}" "${APP:=platform-api}"
-
-DOCKER_IMAGE=$DOCKER_HOST/$DOCKER_NAMESPACE/$APP
+:"${DOCKER_BUILD_CONTEXT=..}" "${DOCKER_BACKEND_PATH=../Dockerfile}" "${TAG:=$COMMIT}" "${APP:=simulators-api}"
 
 DOCKER_PATH=$DOCKER_BACKEND_PATH
-DOCKER_REGISTRY=docker.io
+DOCKER_HOST=docker.io
 DOCKER_NAMESPACE=biosimulations
 
-docker build -f $DOCKER_PATH -t $DOCKER_NAMESPACE/$APP:$TAG --build-arg app=$APP $DOCKER_BUILD_CONTEXT
+USAGE="$0 [-a <App Name> -t <Tag Name>]"
+
+ while getopts 'a:t:' opt
+ do
+     case $opt in
+         a) APP=$OPTARG;;
+         t) TAG=$OPTARG;;
+        \?) echo "ERROR: Invalid option: $USAGE"
+            exit 1;;
+     esac
+done
+
+
+
+DOCKER_IMAGE=$DOCKER_HOST/$DOCKER_NAMESPACE/$APP:$TAG
+echo "Building $DOCKER_IMAGE"
+docker build -f $DOCKER_PATH -t $DOCKER_IMAGE --build-arg app=$APP $DOCKER_BUILD_CONTEXT
