fix: upgraded openapi-generator and forced spec to 3.0.3 to get types

diff --git a/tools/generate-simdata-api-nest-client b/tools/generate-simdata-api-nest-client
--- a/tools/generate-simdata-api-nest-client
+++ b/tools/generate-simdata-api-nest-client
@@ -2,15 +2,27 @@
 
 set -e
 
+generatorCliImage=openapitools/openapi-generator-cli:v7.2.0
+
 # location of this script
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-sim_data_dir="$(dirname "$script_dir")/apps/simdata-api"
+parentDir="$( cd "$( dirname "${script_dir}" )" >/dev/null 2>&1 && pwd )"
+echo "script_dir: ${script_dir}"
+echo "parentDir: ${parentDir}"
 
+sim_data_dir="${parentDir}/apps/simdata-api"
+echo "sim_data_dir: ${sim_data_dir}"
 # spec location
 spec_file=${sim_data_dir}/simdata_api/spec/openapi.yaml
 
 echo "generating openapi spec: ${spec_file}"
 poetry run -C ${sim_data_dir} python ${sim_data_dir}/simdata_api/internal/gen_openapi_spec.py
+
+
+# FastAPI generates a 3.1.0 spec, but the openapi generator only supports 3.0.3.
+# here, we manually change the spec version from 3.1.0 to 3.0.3 and turn off validation
+# https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux
+sed -i '' 's/3.1.0/3.0.3/'  "${spec_file}"
 
 # output location
 lib_dir=${script_dir}/../libs/simdata-api/nest-client
@@ -18,11 +30,20 @@ lib_dir=${script_dir}/../libs/simdata-api/nest-client
 rm -rf ${lib_dir}/src/lib/api/
 rm -rf ${lib_dir}/src/lib/model/
 
+echo "validating openapi.yaml"
+docker run --rm -v ${parentDir}:/repo_root ${generatorCliImage} validate \
+    -i /repo_root/apps/simdata-api/simdata_api/spec/openapi.yaml --recommend
+if [ $? -ne 0 ]; then
+    echo "openapi.yaml is not valid"
+    exit 1
+fi
+
 echo "generating nestjs client"
-npx @openapitools/openapi-generator-cli generate \
+docker run --rm -v ${parentDir}:/repo_root ${generatorCliImage} generate \
     -g typescript-nestjs \
-    -i ${spec_file} \
-    -o ${lib_dir}/src/lib/ \
-    --global-property=skipFormModel=false \
-    --additional-properties=stringEnums=true,enumPropertyNaming=original,nestVersion=9.0.0,supportsES6=true \
-    --reserved-words-mappings abstract=abstract
+    -i /repo_root/apps/simdata-api/simdata_api/spec/openapi.yaml \
+    -o /repo_root/libs/simdata-api/nest-client/src/lib/ \
+    -c /repo_root/tools/simdata-api-nestjs-config.yaml
+    --skip-validate-spec
+
+echo "done"
