ci: fix nx workflow
closes #3758

diff --git a/.github/workflows/buildLintTest.yml b/.github/workflows/buildLintTest.yml
--- a/.github/workflows/buildLintTest.yml
+++ b/.github/workflows/buildLintTest.yml
@@ -86,13 +86,73 @@ jobs:
         name: Start CI Run
         if: always()
 
-      - run: npx nx affected --target=lint --parallel & P1=$! npx nx affected --target=build --prod --parallel & P2=$! npx nx affected --target=test --parallel & P3=$! && wait $P1 $P2 $P3
-        name: Lint Build Test Affected
+      - name: Lint Build Test Affected
         if:  ${{inputs.affectedOnly}}
+        run: |
+          # launch processes concurrently and collect ids of processes
+          npx nx affected --target=lint --parallel &
+          P1=$!
 
-      - run: npx nx run-many --all --target=lint --parallel & P1=$! npx nx run-many --all --target=build --prod --parallel & P2=$! npx nx run-many --all --target=test --parallel & P3=$! && wait $P1 $P2 $P3
-        name: Lint Build Test All
+          npx nx affected --target=build --prod --parallel &
+          P2=$!
+
+          npx nx affected --target=test --parallel &
+          P3=$!
+
+          # wait for processes to finish and collect exit codes
+          wait $P1
+          S1=$?
+
+          wait $P2
+          S2=$?
+
+          wait $P3
+          S3=$?
+
+          # find highest exit code
+          S_ARR=($S1 $S2 $S3)
+          S=${S_ARR[0]}
+          for n in "${S_ARR[@]}" ; do
+              ((n > S)) && S=$n
+          done
+
+          # return highest exit code
+          exit $S
+
+      - name: Lint Build Test All
         if: ${{!inputs.affectedOnly}}
+        run: |
+          # launch processes concurrently and collect ids of processes
+          npx nx run-many --all --target=lint --parallel &
+          P1=$!
+
+          npx nx run-many --all --target=build --prod --parallel &
+          P2=$!
+
+          npx nx run-many --all --target=test --parallel &
+          P3=$!
+
+          # wait for processes to finish and collect exit codes
+          wait $P1
+          S1=$?
+
+          wait $P2
+          S2=$?
+
+          wait $P3
+          S3=$?
+
+          # find highest exit code
+          S_ARR=($S1 $S2 $S3)
+          S=${S_ARR[0]}
+          for n in "${S_ARR[@]}" ; do
+              ((n > S)) && S=$n
+          done
+
+          # return highest exit code
+          exit $S
+
+
 
       - name: Stop CI run
         run: npx nx-cloud stop-all-agents
