fix: apply correct linting rules to angular component templates

diff --git a/.github/workflows/buildLintTest.yml b/.github/workflows/buildLintTest.yml
--- a/.github/workflows/buildLintTest.yml
+++ b/.github/workflows/buildLintTest.yml
@@ -83,15 +83,53 @@ jobs:
       - name: Lint Build Test Affected
         if:  ${{inputs.affectedOnly}}
         run: |
-          npx nx affected --target=lint --parallel & \
-          npx nx affected --target=build --prod --parallel & \
-          npx nx affected --target=test --parallel
+          # launch processes concurrently and collect ids of processes
+          npx nx affected --target=lint --parallel &
+          P1=$!
+          npx nx affected --target=build --prod --parallel &
+          P2=$!
+          npx nx affected --target=test --parallel &
+          P3=$!
+          # wait for processes to finish and collect exit codes
+          wait $P1
+          S1=$?
+          wait $P2
+          S2=$?
+          wait $P3
+          S3=$?
+          # find highest exit code
+          S_ARR=($S1 $S2 $S3)
+          S=${S_ARR[0]}
+          for n in "${S_ARR[@]}" ; do
+              ((n > S)) && S=$n
+          done
+          # return highest exit code
+          exit $S
       - name: Lint Build Test All
         if: ${{!inputs.affectedOnly}}
         run: |
-          npx nx run-many --all --target=lint --parallel & \
-          npx nx run-many --all --target=build --prod --parallel & \
-          npx nx run-many --all --target=test --parallel
+          # launch processes concurrently and collect ids of processes
+          npx nx run-many --all --target=lint --parallel &
+          P1=$!
+          npx nx run-many --all --target=build --prod --parallel &
+          P2=$!
+          npx nx run-many --all --target=test --parallel &
+          P3=$!
+          # wait for processes to finish and collect exit codes
+          wait $P1
+          S1=$?
+          wait $P2
+          S2=$?
+          wait $P3
+          S3=$?
+          # find highest exit code
+          S_ARR=($S1 $S2 $S3)
+          S=${S_ARR[0]}
+          for n in "${S_ARR[@]}" ; do
+              ((n > S)) && S=$n
+          done
+          # return highest exit code
+          exit $S
       - name: Stop CI run
         run: npx nx-cloud stop-all-agents
         if:  always()
@@ -111,7 +149,7 @@ jobs:
     timeout-minutes: 60
     strategy:
       matrix:
-        agent: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
+        agent: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
     steps:
       - uses: actions/checkout@v2
 
