Catching errors on non-existing targets

diff --git a/.github/workflows/ci2.yml b/.github/workflows/ci2.yml
--- a/.github/workflows/ci2.yml
+++ b/.github/workflows/ci2.yml
@@ -139,7 +139,17 @@ jobs:
 
       - name: Lint library or app
         working-directory: ./biosimulations
-        run: nx run ${{ matrix.libOrApp }}:lint
+        run: |
+          set -e
+          { ERROR_MSG=$(nx run ${{ matrix.libOrApp }}:lint 2>&1 1>&3-) ;} 3>&1
+          ERROR_CODE=$?
+          if [[ $ERROR_MSG =~ "An unhandled exception occurred: Project target does not exist." ]]; then
+              echo "Target does not exist"
+              exit 0
+          else
+              echo "$ERROR_MSG"
+              exit $ERROR_CODE
+          fi
 
   build:
     name: Build app
@@ -257,7 +267,17 @@ jobs:
           MANAGEMENT_DOMAIN: ${{ secrets.MANAGEMENT_DOMAIN }}
           MANAGEMENT_ID: ${{ secrets.MANAGEMENT_ID }}
           MANAGEMENT_SECRET: ${{ secrets.MANAGEMENT_SECRET }}
-        run: nx run ${{ matrix.libOrApp }}:test --code-coverage --codeCoverage
+        run: |
+          set -e
+          { ERROR_MSG=$(nx run ${{ matrix.libOrApp }}:test --code-coverage --codeCoverage 2>&1 1>&3-) ;} 3>&1
+          ERROR_CODE=$?
+          if [[ $ERROR_MSG =~ "An unhandled exception occurred: Project target does not exist." ]]; then
+              echo "Target does not exist"
+              exit 0
+          else
+              echo "$ERROR_MSG"
+              exit $ERROR_CODE
+          fi
 
       - name: Upload coverage data to Codecov
         uses: codecov/codecov-action@v1.0.3
