refactor: cleaned up levels of headings of changelog

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -8,7 +8,7 @@ on:
      NPM_TOKEN:
         required: true
      GPG_PRIVATE_KEY:
-        required: true     
+        required: true
 jobs:
   Release:
     runs-on: ubuntu-latest
@@ -17,7 +17,8 @@ jobs:
         with:
           token: ${{secrets.GH_RELEASE_TOKEN}}
           ref: dev
-      - name: Configure CI Git User
+
+      - name: Configure Git user
         run: |
           git config --global user.name 'BioSimulations-Daemon'
           git config --global user.email 'biosimulationsdaemon@gmail.com'
@@ -43,5 +44,32 @@ jobs:
           GIT_AUTHOR_EMAIL: "biosimulationsdaemon@gmail.com"
           GIT_COMMITTER_NAME: "BioSimulations-Daemon"
           GIT_COMMITTER_EMAIL: "biosimulationsdaemon@gmail.com"
-
         run: npx semantic-release
+
+      # Clean up changelog
+      - name: Pull changes
+        run: |
+          git fetch --all
+          git reset --hard origin/dev
+
+      - name: Clean up changelog
+        run: tools/clean-up-changelog
+
+      - name: Commit changelog
+        id: commit-changelog
+        run: |
+          git add docs/CHANGELOG.md
+          git commit -m "chore(release): cleaned up changelog [skip ci]"
+          if [[ $? = 0 ]]; then
+            changed=1
+          else
+            changed=0
+          fi
+          echo "::set-output name=changed::$changed"
+
+      - name: Push the updated changelog
+        if: steps.commit-changelog.outputs.changed == '1'
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: dev
